@url = http://localhost:3000/checks
### Post checks
POST {{url}}/
 content-type: application/json 
 Cache-Control: no-cache
 token: o4xsglo1tvpdiafs6th0

{
  "protocol": "http",
  "url": "google.com",
  "method":"get",
  "successCodes": [200,201],
  "timeoutSeconds": 3
}