@url = http://localhost:3000/tokens
### Post token
POST {{url}}/
 content-type: application/json 
 Cache-Control: no-cache

{
  "phone": "1112223388",
  "password": "quituti"
}

### Get token
@id = a67i50q3kjbu41f1se0u
GET {{url}}?id={{id}}
 content-type: application/json 
 Cache-Control: no-cache

### Get token
PUT {{url}}
 content-type: application/json 
 Cache-Control: no-cache

 {
   "id": "m2bwfarl0vh8c8hi4ro2",
   "extend": true
 }

### Delete users
DELETE {{url}}?id=5jvxbihchw25w1qa5nn5
 content-type: application/json 
 Cache-Control: no-cache