@url = http://localhost:3000/users

### Get users
@phoneNumber = 1112223334
@token = b42vz4pxcw47w0hmrp24
GET {{url}}?phone={{phoneNumber}}
 content-type: application/json 
 Cache-Control: no-cache
 token: {{token}}

### Post users
POST {{url}}
 content-type: application/json 
 Cache-Control: no-cache

{
  "firstName": "Xablaus2",
  "lastName": "Baltezan2",
  "phone": "1112223388",
  "password": "quituti",
  "tosAgreement": true
}

### Put users
PUT {{url}}
 content-type: application/json 
 Cache-Control: no-cache

{
  "firstName": "Xablaus2",
  "lastName": "S. Baltezan2",
  "phone": "5551234567",
  "password": "quituti"
}

### Delete users
DELETE {{url}}?phone=1112223388
 content-type: application/json 
 Cache-Control: no-cache
 token: b42vz4pxcw47w0hmrp24
