@url = http://localhost:3000/users

### Get users
@phoneNumber = 1112223334
@token = gix2jxts3sg5vs7p5ht4
GET {{url}}?phone={{phoneNumber}}
 content-type: application/json 
 Cache-Control: no-cache
 token: {{token}}

### Post users
POST {{url}}
 content-type: application/json 
 Cache-Control: no-cache

{
  "firstName": "Xablaus",
  "lastName": "Baltezan",
  "phone": "1112223334",
  "password": "quituti",
  "tosAgreement": true
}

### Put users
PUT {{url}}
 content-type: application/json 
 Cache-Control: no-cache

{
  "firstName": "Xablaus",
  "lastName": "S. Baltezan",
  "phone": "1112223334",
  "password": "quituti"
}

### Delete users
DELETE {{url}}?phone=1112223334
 content-type: application/json 
 Cache-Control: no-cache
